### ISSUE TITLE
1.4.0 Release

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/promises#107]
Looks like there are a couple of fixes merged into master that have not yet made it into a release. Looking at the outstanding PRs that could be merged or closed right now, we have:

#### Looks good to merge to me:

1. ~https://github.com/guzzle/promises/pull/98~ Done: merged
2. ~https://github.com/guzzle/promises/pull/105~ Done: merged

#### I think should be closed:

1. ~https://github.com/guzzle/promises/pull/83~ Done: closed
2. ~https://github.com/guzzle/promises/pull/91~ Done: closed

#### Not immediately obvious, risky, or unfinished:

1. ~https://github.com/guzzle/promises/pull/62~ Done: closed
2. https://github.com/guzzle/promises/pull/70
3. ~https://github.com/guzzle/promises/pull/95~ Done: merged
4. https://github.com/guzzle/promises/pull/104

**Comment by p-golovin** [comment]
Hi,
is there any plans on this release?

Current version get warnings on php 7.4:

 222 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 257 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 313 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead

**Comment by GrahamCampbell** [comment]
I think the change that removed PHP 5.5 is a blocker actually. We need to add it back in so that 1.4.0 can be included in the next phar release of Guzzle 6.

**Comment by GrahamCampbell** [comment]
Done: https://github.com/guzzle/promises/pull/110.

**Comment by GrahamCampbell** [comment]
Actually, there is a new feature committed since 1.3.1, so next will be 1.4.0.

**Comment by GrahamCampbell** [comment]
I'll prep a release PR.
