### ISSUE TITLE
cancel() not bubbling up to recursive promises?

### ISSUE THREAD

**Issue by mikegreiling** [guzzle/promises#13]
The following code yields no response.  Shouldn't it trigger the `cancel()` method in the inner promise?  Is this a bug or a feature?

	$promise = new Promise();
	$promise->resolve(true);
	$promise
		->then(function() {
			return (new Promise())
				->then(function() {
					echo "inner-promise fulfilled!";
				})
				->otherwise(function() {
					echo "inner-promise rejected!";
				});
		})
		->then(function() {
			echo "promise fulfilled!";
		})
		->otherwise(function() {
			echo "promise rejected!";
		})
		->cancel();

	\GuzzleHttp\Promise\queue()->run();

**Comment by mtdowling** [comment]
cancellation of A+ promises has never been formally spec'd out, so there's no standard to compare against.

I just took a look at ReactPHP's promise library, and they have the same behavior as Guzzle:

```php
<?php
require 'vendor/autoload.php';

$d = new React\Promise\Deferred();
$d->resolve('test');

$d->promise()
    ->then(function() {
        $d2 = new React\Promise\Deferred();
        return $d2->promise()
            ->then(function() {
                echo "inner-promise fulfilled!";
            })
            ->otherwise(function() {
                echo "inner-promise rejected!";
            });
    })
    ->then(function() {
        echo "promise fulfilled!";
    })
    ->otherwise(function() {
        echo "promise rejected!";
    })
    ->cancel();
```

Cancelling a promise will cancel an incomplete promise -- it does not cancel promises that are in the queue of promises that are already completed. It also does not chain cancellation functions together of resolved promises because a resolved promise's cancellation method is no longer valid.

I'm not really sure how else this could work. I'll close this, but I'd be happy to take a look at a pull request as a proposal for changes.
