### ISSUE TITLE
Confused about the order of the ->then callback resolution

### ISSUE THREAD

**Issue by brutuscat** [guzzle/promises#33]
I would expect the 3 `->then` to come up in the 3rd place. Is this a bug or as per design? What is the logic behind it?

It looks like a bug because of chaining `->then()->then`, since on the fair race, one then comes after the other but always on the promise object instead of in the return value of the last then...

```php

$cheating = new GuzzleHttp\Promise\Promise(
    function () use(&$cheating){
        $cheating->resolve(null);
        echo "\n--- Finish line ---\n";
    }
);

$cheating->then(function() {
    echo "I'm the #1!\n";
})->then(function() {
    echo "I'm the #2...\n";
});

$cheating->then(function() {
    echo "Haha! And I'm the #3? Nop!\n";
});

$cheating->wait(false);

$fairRace = new GuzzleHttp\Promise\Promise(
    function () use(&$fairRace){
        $fairRace->resolve(null);
        echo "\n--- Finish line on Fair Race ---\n";
    }
);

$fairRace->then(function() {
    echo "I'm the #1!\n";
});
$fairRace->then(function() {
    echo "I'm the #2...\n";
});

$fairRace->then(function() {
    echo "I'm the #3 :(\n";
});

$fairRace->wait(false);
```

This is the output I see:
```

--- Finish line ---
I'm the #1!
Haha! And I'm the #3? Nop!
I'm the #2...

--- Finish line on Fair Race ---
I'm the #1!
I'm the #2...
I'm the #3 :(
```

My composer.lock says I'm using 1.2
```
            "version": "1.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/promises.git",
                "reference": "c10d860e2a9595f8883527fa0021c7da9e65f579"
```

**Comment by alexeyshockov** [comment]
I think that it's not a bug, because the evaluation order is not defined anywhere.

Currently Guzzle executes all handlers (siblings) of a promise first, and then executes all handler of "child" promises ([code](https://github.com/guzzle/promises/blob/master/src/Promise.php#L154)). It can exposed like this:

```
cheating
|-- then_1
    `-- then_2
`-- then_3

fairRace
|-- then_1
|-- then_2
`-- then_3
``` 

Your example shows the same but in a different form.

**Comment by brutuscat** [comment]
@alexeyshockov if this is the expected behavior I think it should be documented, because the readme states:

>These callbacks are triggered only once and in the order in which they were added.

And clearly the order in which they were added is being honored...

**Comment by mtdowling** [comment]
Anyone know how other promise libraries like bluebird for example handle this?

**Comment by brutuscat** [comment]
@mtdowling it behavies in the same way https://jsfiddle.net/6yz9Lh6t/ which it kinda makes my point valid because of JS async nature... It just feel weird. I'm ok with it as long "that's the way to do it" but it feels weird.

**Comment by mtdowling** [comment]
> it behavies in the same way https://jsfiddle.net/6yz9Lh6t/ which it kinda makes my point valid because of JS async nature

Can you clarify? If Guzzle behaves the same way as other promise libraries, how does that make Guzzle's behavior weird?

**Comment by brutuscat** [comment]
@mtdowling I don't remember why now, but the whole idea behind promises is to have callback-async code simpler to reason about, making it look and feel like sequential code.

Now clearly that's not the case!

**Comment by schnittstabil** [comment]
That behavior is known as [*always async*](https://github.com/domenic/promise-tests#always-async), and yes it is expected, and yes it makes the code easier to reason about :wink:

[Promises/A+ 2.2.4](https://promisesaplus.com/#point-34):
> `onFulfilled` or `onRejected` must not be called **until the execution context stack contains only platform code**. [3.1].

[[3.1]](https://promisesaplus.com/#point-67):
> … In practice, this requirement ensures that `onFulfilled` and `onRejected` execute asynchronously, **after the event loop turn in which `then` is called**, and with a fresh stack. …

Yes, the specs leave room for some unfortunate interpretations, but Promise/A+ becomes less and less important, because ES2015 Promises are landed, which explicitly demands *always async* (see&nbsp;8.b.&nbsp;at&nbsp;[25.4.5.3.1&nbsp;PerformPromiseThen](http://www.ecma-international.org/ecma-262/6.0/#sec-performpromisethen)).

--
About your example:

```php
$cheating->then(function() {
    echo "I'm the #1!\n";
})->then(function() {
    echo "I'm the #2...\n";
});

$cheating->then(function() {
    echo "Haha! And I'm the #3? Nop!\n";
});
```

This is essentially the same as:
```php
function f1 () {
    echo "I'm the #1!\n";
}
function f2 () {
    echo "I'm the #2...\n";
}
function f3() {
    echo "Haha! And I'm the #3? Nop!\n";
}

$a = $cheating->then(f1);
$a->then(f2);
$cheating->then(f3);
```

1. When `$cheating` is fulfilled `f1` and `f3` are called in the next turn of the event loop – [in exactly that order](https://promisesaplus.com/#point-37).
2. After `f1` was executed, `$a` is fulfilled and `f2` is called in the next turn of the event loop.

**Comment by brutuscat** [comment]
@schnittstabil thank you for your explanation. Tough now I understand the reasoning about this behavior, it does look weird for someone that did not read that doc and that just "knows" that promises are to make async code to look like sequential code.

Anyway, thank you for the insight, I'll keep it in mind!

Closing this since has been explained properly now.
