### ISSUE TITLE
Coroutine issue with 1.3.0 release

### ISSUE THREAD

**Issue by cjyclaire** [guzzle/promises#54]
Latest `1.3.0` release includes `coroutine` changes that seems break `aws-sdk-php` behaviors.
`coroutine` is used in our [`instanceCredentialProvider`](https://github.com/aws/aws-sdk-php/blob/33e8f7083fcb54fd926a8569cb81a0795e8c2633/src/Credentials/InstanceProfileProvider.php#L48), which is [chained]((https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L101)) in our [`defaultCredentialProvider`](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L72)

This problem is related to guzzle because there has been no related code changes in our repo, and when downgrade to `1.2.0` fix the problem. 

Personally, I'm having trouble in reproducing the issue locally or with a new ubuntu ec2 instance, and I'm still woking on reproducing it since many customer have reported seeing this issue happening.

Related issue:
aws/aws-sdk-php#1125
guzzle/guzzle#1668

Possible reproduce repo: https://github.com/reproduce/guzzle/tree/issue1668

Open this issue here as well just to have more attention, background and thoughts here. :)

**Comment by sagikazarmark** [comment]
As a sidenote: According to https://github.com/aws/aws-sdk-php/issues/1125#issuecomment-263603703 the issue occurs when chaining and memoizing is done. I don't say the issue is not in this repo, but we should consider that maybe AWS SDK relied on a side effect which doesn't work anymore.

The linked reproduction environment shows the actual situation I think, since the example codes reproduce the reported behaviour, downgrading solves the issue.
