### ISSUE TITLE
Promises callbacks not called until shutdown

### ISSUE THREAD

**Issue by oligriffiths** [guzzle/promises#69]
Hi

From the guide in the readme:

```php
use GuzzleHttp\Promise\Promise;

$promise = new Promise();
$promise
    ->then(function ($value) {
        // Return a value and don't break the chain
        return "Hello, " . $value;
    })
    // This then is executed after the first then and receives the value
    // returned from the first then.
    ->then(function ($value) {
        echo $value;
    });

// Resolving the promise triggers the $onFulfilled callbacks and outputs
// "Hello, reader".
$promise->resolve('reader.');
```

Should output `"Hello, reader".`

However, this doesn't happen until it appears a shutdown handler is called: https://github.com/guzzle/promises/blob/master/src/TaskQueue.php#L21 or the `waitIfPending()` method is called.

If a promise is resolved manually, then the callbacks DO NOT fire. I can't seem to work out if this is intentional or a bug, it doesn't make sense that the handlers are called only in one scenario of *waiting* for a promise.

Can someone explain.

Thanks

**Comment by mtdowling** [comment]
This is intentional. You need to call wait on a promise, tick the promise queue manually, or allow the queue to be ticked on shutdown to fire callbacks. This prevents recursion when resolving promises because recursion in callbacks of promises could cause a stack overflow. This is recommended by the promises/A+ spec: https://promisesaplus.com/#point-34.

You can tick the queue using the following code:

```php
GuzzleHttp\Promise\queue->run();
```

**Comment by oligriffiths** [comment]
@mtdowling this seems odd that I can resolve or reject a promise on the public interface, and the handlers are NOT called, yet if I *wait* then the handlers are called.

**Comment by sagikazarmark** [comment]
Resolution/rejection is available in the public API, because in theory it can happen any time during the execution: eg. a promise can be resolved/rejected by a middleware and not necessarily by the handler. I can't think of many use cases where you would resolve/reject manually, outside of the execution flow though.

**Comment by oligriffiths** [comment]
Given that the wait function is optional, there is actually no way to resolve/reject a promise other than the public interface. The example in the reader does not work in a long running script, you *have* to wait for the shutdown function to trigger the queue. It shouldn't work one way for one circumstance and a different way for another.

**Comment by sagikazarmark** [comment]
As said, this is intentional, is in accordance with the linked specifications.

The async nature of promises does not have any guarantees on when a callback will be invoked.

If you want a promise to settle after resolution, you can do two things:

- call wait on the relevant promise, if you have it
- tick the promise queue

**Comment by jvitela** [comment]
This works for me (with Lumen)

```
use GuzzleHttp\Promise\FulfilledPromise;

class FulfilledPromiseTest extends TestCase
{
  public function testResolveCallback()
  {
    // Instance objects first
    $console = Mockery::mock('console');
    $promise = new FulfilledPromise('success');

    // Configure expectations
    $console->shouldReceive('log')->once()->with('success');

    // Execute test
    $p = $promise->then(function($response) use($console) {
      $console->log($response);
    });

    //  Tick the promise queue to trigger the callback
    $p->wait();
    \GuzzleHttp\Promise\queue();
  }
}
```
